import fs from 'node:fs/promises';
import { extractClasses } from './extractor.js';

export async function generateTypes(filePath: string, content: string): Promise<void> {
	const classNames = extractClasses(content);
	const declarationPath = `${filePath}.d.ts`;
	const inner =
		classNames.length > 0 ?
			`\n${classNames.map(n => `\t"${n}": "${n}",`).join('\n')}\n`
		:	'';

	const template = `/* Generated by HermitCSS — do not edit manually */
export const classes = {${inner}} as const;
declare const compiled: string;
export default compiled;
`;

	await fs.writeFile(declarationPath, template, 'utf-8');
}
